import math
import re

inner_verts = []
outer_verts = []

# Get deduplicated vertices from files
with open("ScienceInner.stl") as inner:
  inner_text = inner.read()
  verts = re.findall(r"vertex\s+([-0-9.]+)\s+([-0-9.]+)\s+([-0-9.]+)", inner_text)
  inner_verts = list(set(verts))
with open("ScienceOuter.stl") as outer:
  outer_text = outer.read()
  verts = re.findall(r"vertex\s+([-0-9.]+)\s+([-0-9.]+)\s+([-0-9.]+)", outer_text)
  outer_verts = list(set(verts))

# Convert to floats
inner_verts = [(float(x), float(y), float(z)) for x, y, z in inner_verts]
outer_verts = [(float(x), float(y), float(z)) for x, y, z in outer_verts]
inner_verts.sort()
outer_verts.sort()

# Find edges between inner and outer
edges = []
for (inner_i, inner) in enumerate(inner_verts):
  threshold = 0.25
  close_enough = []
  for (outer_i, outer) in enumerate(outer_verts):
    if math.dist(inner, outer) < threshold:
      close_enough.append((outer_i, outer))
  assert(len(close_enough) in [5, 6])

  for outer_i, outer in close_enough:
    edges.append((inner_i, len(inner_verts) + outer_i))

# Find edges between outer vertices
for (a_i, a) in enumerate(outer_verts):
  threshold = 0.25
  close_enough = []
  for (b_i, b) in enumerate(outer_verts):
    if a == b:
      continue
    if math.dist(a, b) < threshold:
      close_enough.append((b_i, b))
  assert(len(close_enough) in [1, 3])

  for b_i, b in close_enough:
    edges.append((len(inner_verts) + a_i, len(inner_verts) + b_i))

# Scale down inner vertices
s = 0.9
inner_verts = [(s * x, s * y, s * z) for x, y, z in inner_verts]

# Emit Odin code
with open("../science.odin", "w") as out:
  out.write("// Generated by scripts/scienceinator.py. DO NOT EDIT!\n")
  out.write("package screensaver\n")
  out.write("\n")
  out.write(f"num_inner_verts :: {len(inner_verts)}\n")
  out.write("verts := []v3 {\n")
  for vert in inner_verts + outer_verts:
    out.write("\t{%f, %f, %f},\n" % vert)
  out.write("}\n")
  out.write("\n")
  out.write("edges := [][2]int {\n")
  for edge in edges:
    out.write("\t{%d, %d},\n" % edge)
  out.write("}\n")
